### ISSUE TITLE
个人URL更新后logo链接处未更新

### ISSUE THREAD

**Issue by yuhangch** [gikiapp/giki.app#1]
### 问题描述
在setting页更改个人URL后，点击左上方`giki`logo，仍然跳转至原个人URL。

### 另一点小请求
鼠标悬停在♥️时候希望可以和右下角tag一样切换到小手。

**Comment by metrue** [comment]
@YuhangCh 谢谢你的反馈，修复已经进行中喽。

**Comment by metrue** [comment]
已经修复喽 @YuhangCh

**Comment by yuhangch** [comment]
👍
